### ISSUE TITLE
Minutes not displaying correctly

### ISSUE THREAD

**Issue by redburn** [phaselden/FlipIt#2] opened 2021-01-13 16:57 UTC
It is currently 17:53 (or 5:53pm) but the screensaver displays 5:5, as shown here:

![2021-01-13 17_56_31-Greenshot](https://user-images.githubusercontent.com/3878542/104483685-b006fc00-55c8-11eb-80a7-5337bfa29f22.png)

**Comment by phaselden** [comment] 2021-01-15 00:06
Yes, as @schlambers said, it doesn't look like you have the right font installed. Please try that and let me know how you go.

BTW I have been thinking about ways to avoid having to download and install the font manually. For example, install it automatically or not require the font at all and instead use some SVG images.

**Comment by redburn** [comment] 2021-01-15 14:12
Cheers, obviously I did not read the requirements properly.

Looks better now, but not quite the same as the screenshot in the README. The digits are not quite centered vertically:
![2021-01-15 15_08_51-Greenshot](https://user-images.githubusercontent.com/3878542/104736846-d1d8be00-5743-11eb-9497-a133a6f5cb5f.png)

**Comment by jurczewski** [comment] 2021-01-15 14:27
I wonder, if it is possible to change it to look more similar to Fliqlo. 

Here is Linux version of Fliqlo with Fliqlo's **exact** font: (no need for downloading fonts separately)
[https://github.com/alexanderk23/gluqlo](https://github.com/alexanderk23/gluqlo)

**Comment by phaselden** [comment] 2021-01-17 23:30
@redburn The alignment is by design. If you look at images of "real" physical flip clocks they are also not 100% centered. However I have just realised that the split in clocks (and other some other apps) tends to be lower rather than higher.

**Comment by phaselden** [comment] 2021-01-18 00:14
@jurczewski If you download the TTF in gluqlo, and look at the file details it says "Fliqlo". While there is no copyright info in the file, I am a little concerned about its licensing.

**Comment by redburn** [comment] 2021-01-18 10:10
@phaselden OK, it just looked different from the screenshot in the readme. You're right, it does like the split is usually lower.

I could create an installer for the screensaver that automatically installs the font.

**Comment by jurczewski** [comment] 2021-01-18 10:25
> @jurczewski If you download the TTF in gluqlo, and look at the file details it says "Fliqlo". While there is no copyright info in the file, I am a little concerned about its licensing.

I also says "Name of font: Helvetica"
![image](https://user-images.githubusercontent.com/24575781/104902767-6b3fe400-597f-11eb-934e-bb26fb44f98d.png)

To be honest I have no knowledge about fonts, but can it be just Helvetica renamed to Fliqlo?

**Comment by phaselden** [comment] 2021-01-18 12:14
Thanks @redburn, I might take you up on that but @jurczewski has found (thanks!) the font is Helvetica LT which I suspect I can use for free and, if so, can embed it into the exe.

**Comment by phaselden** [comment] 2021-01-23 15:08
The font issues were addressed in a previous beta and the digit alignment is fixed in beta 3 of v1.2

**Closed by phaselden** 2021-01-23 15:08 UTC
